# Generated by Django 2.1.4 on 2019-01-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='W12scan_domains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=128)),
                ('pid', models.CharField(max_length=128)),
                ('add_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='W12scan_ips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=128)),
                ('pid', models.CharField(max_length=128)),
                ('add_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='W12scan_properly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('descript', models.TextField()),
                ('ips', models.TextField()),
                ('domains', models.TextField()),
                ('pid', models.CharField(max_length=128)),
                ('add_time', models.DateField(auto_now=True)),
            ],
        ),
    ]
