# Generated by Django 2.1.4 on 2019-01-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='W12scan_domains',
            new_name='domains',
        ),
        migrations.RenameModel(
            old_name='W12scan_ips',
            new_name='ips',
        ),
        migrations.RenameModel(
            old_name='W12scan_properly',
            new_name='properly',
        ),
    ]
