# Generated by Django 2.1.4 on 2019-02-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190128_1515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='domains',
        ),
        migrations.DeleteModel(
            name='ips',
        ),
        migrations.RemoveField(
            model_name='properly',
            name='pid',
        ),
    ]
