# Generated by Django 2.1.7 on 2019-04-18 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('email', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=32, unique=True)),
            ],
        ),
    ]
